files:
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/settings.yml
prBody: 'Привет! Я – бот для гитхаба и я тут сделаю немного работы за тебя. Например, в этом PR я добавлю стандартные настройки для нашей организации.'
